"""
Stage 2 of the pipeline: LEARNING-TO-RANK RE-RANKER (LightGBM LambdaMART).

THEORY -> CODE NOTES
--------------------
WHY A SECOND STAGE AT ALL?
    Stage 1 is deliberately crippled: the user and item never meet until a
    single dot product at the very end. That restriction is what makes it fast
    enough to search millions of items -- but it means the model cannot learn
    interactions like "this user likes Horror ONLY when it is also recent".

    Stage 2 drops the restriction. It sees the user and the candidate together
    and can build arbitrary feature crosses. It is far more expressive, and far
    too slow to run over the whole catalogue -- which is fine, because stage 1
    already cut the catalogue down to ~100 candidates.

    Cheap-and-crude then expensive-and-sharp. That is the whole design.

WHY LAMBDARANK INSTEAD OF PLAIN CLASSIFICATION?
    We could train a binary classifier: "will the user click this? yes/no".
    But that optimises each item in isolation, and we do not care about
    calibrated per-item probabilities -- we care about the ORDER of the list.

    LambdaRank optimises the order directly. During training it looks at PAIRS
    of items within the same user's candidate list and asks "is the positive
    ranked above this negative?", weighting each swap by how much fixing it
    would improve NDCG. Swapping positions 1 and 2 matters much more than
    swapping 80 and 81, and the loss reflects that. Plain classification treats
    both swaps identically.

    That is why LightGBM needs the `group` argument -- it has to know which
    rows belong to the same user's list, since comparisons only make sense
    inside a list.

AVOIDING LEAKAGE -- the part that is easy to get wrong
    The re-ranker is trained on candidates generated by stage 1. If we trained
    it on the same held-out items we later evaluate on, the reported numbers
    would be fiction. So:
        training rows -> candidates scored against the VALIDATION item
        eval rows     -> candidates scored against the TEST item
    and every feature is computed ONLY from data available before that point.
"""

import numpy as np
import pandas as pd
import lightgbm as lgb

from two_tower import score_all_items, ranking_metrics
from data import GENRE_NAMES


N_CANDIDATES = 100        # how many stage-1 survivors stage 2 re-ranks


def build_features(ds, scores, target_users, target_items, n_candidates=N_CANDIDATES):
    """Turn stage-1 candidates into a flat feature table for the ranker.

    One row per (user, candidate_item). Label is 1 for the held-out item the
    user actually engaged with, 0 for the other candidates.
    """
    # --- item-side statistics, computed from TRAIN ONLY ---------------------
    train_items = ds.train.item.to_numpy()
    item_pop = np.bincount(train_items, minlength=ds.n_items).astype(np.float64)
    item_pop_norm = item_pop / max(item_pop.max(), 1)

    # --- user-side statistics ----------------------------------------------
    user_activity = ds.train.groupby("user").size().reindex(
        range(ds.n_users), fill_value=0).to_numpy().astype(np.float64)

    # Each user's average genre profile: the mean genre vector over everything
    # they liked in training. Lets the ranker compute "does this candidate
    # match the genres this person actually watches?" -- a user x item cross
    # that stage 1 structurally cannot represent.
    user_genre = np.zeros((ds.n_users, ds.genres.shape[1]), dtype=np.float64)
    for u, group in ds.train.groupby("user"):
        user_genre[u] = ds.genres[group.item.to_numpy()].mean(axis=0)

    rows_user, rows_item, rows_label, rows_score, rows_rank = [], [], [], [], []
    for u, true_item in zip(target_users, target_items):
        row = scores[u]
        # top-N candidates from stage 1 (argpartition is O(n), not a full sort)
        cand = np.argpartition(-row, n_candidates)[:n_candidates]
        cand = cand[np.isfinite(row[cand])]          # drop masked/seen items

        # The true item may not have survived stage 1. That is a genuine
        # retrieval miss and stage 2 cannot recover it -- a re-ranker can only
        # reorder what it was handed. Such lists contain no positive: they
        # generate no training pairs for LambdaRank (harmless), and at eval
        # time they are counted as failures rather than quietly dropped.
        # This ceiling is why "candidate recall" is reported below: it is the
        # hard upper bound on what the whole pipeline can achieve.
        # sort candidates by stage-1 score so we can hand the ranker the
        # POSITION stage 1 assigned, not just the raw score. Rank is often
        # more robust than score, because scores are not comparable across
        # users while "you were 3rd on this user's list" always means the same.
        order = np.argsort(-row[cand])
        cand = cand[order]

        rows_user.append(np.full(len(cand), u))
        rows_item.append(cand)
        rows_label.append((cand == true_item).astype(int))
        rows_score.append(row[cand])
        rows_rank.append(np.arange(len(cand), dtype=np.float64))

    users = np.concatenate(rows_user)
    items = np.concatenate(rows_item)
    labels = np.concatenate(rows_label)
    tt_score = np.concatenate(rows_score)
    tt_rank = np.concatenate(rows_rank)
    group_sizes = [len(r) for r in rows_item]

    # --- the features stage 1 structurally CANNOT represent ----------------
    # A two-tower model scores with a single dot product, so it can never
    # express "this user likes Horror only when it is also highly rated".
    # Every user x item cross below is exactly the kind of interaction the
    # re-ranker exists to capture.

    # scalar genre affinity: how well the candidate matches the user's taste
    genre_affinity = np.einsum("ij,ij->i", user_genre[users], ds.genres[items])

    feats = {
        "two_tower_score": tt_score,                   # what stage 1 thought
        "two_tower_rank": tt_rank,                     # where stage 1 put it
        "item_popularity": item_pop_norm[items],
        "item_mean_rating": ds.item_mean_rating[items],
        "item_n_ratings": ds.item_n_ratings[items],
        "item_year": ds.item_year[items],
        "item_n_genres": ds.genres[items].sum(axis=1),
        "user_activity": user_activity[users],
        "genre_affinity": genre_affinity,
    }

    # per-genre affinity: 19 separate features instead of one scalar, so the
    # trees can learn genre-specific rules ("this user's Drama affinity
    # predicts clicks, their Action affinity does not") rather than being
    # forced to treat all genres as interchangeable.
    per_genre = user_genre[users] * ds.genres[items]
    for gi, gname in enumerate(GENRE_NAMES):
        feats[f"aff_{gname}"] = per_genre[:, gi]

    return pd.DataFrame(feats), labels, np.array(group_sizes), users, items


def train_reranker(ds, model, device="cpu", verbose=True):
    """Train LambdaMART on validation-labelled candidates, evaluate on test."""
    # --- TRAINING candidates: stage-1 scores WITHOUT the val item masked, so
    #     the val item can appear as the positive in each list.
    train_scores = score_all_items(ds=ds, model=model, mask_val=False, device=device)
    Xtr, ytr, gtr, _, _ = build_features(
        ds, train_scores, ds.val.user.to_numpy(), ds.val.item.to_numpy())

    # --- EVAL candidates: val item now masked (the user has "seen" it), and
    #     the positive is the test item.
    eval_scores = score_all_items(ds=ds, model=model, mask_val=True, device=device)
    Xte, yte, gte, ev_users, ev_items = build_features(
        ds, eval_scores, ds.test.user.to_numpy(), ds.test.item.to_numpy())

    ranker = lgb.LGBMRanker(
        objective="lambdarank",
        metric="ndcg",
        ndcg_eval_at=[10],
        n_estimators=300,
        learning_rate=0.05,
        num_leaves=31,
        min_child_samples=20,
        random_state=0,
        verbose=-1,
    )
    ranker.fit(
        Xtr, ytr, group=gtr,
        eval_set=[(Xte, yte)], eval_group=[gte],
        callbacks=[lgb.early_stopping(30, verbose=False)],
    )

    # --- score the eval candidates and find where the true item landed ------
    pred = ranker.predict(Xte)
    ranks_reranked, ranks_stage1 = [], []
    n_lists_with_positive = 0
    offset = 0
    for size in gte:
        sl = slice(offset, offset + size)
        offset += size
        lab = yte[sl]
        if lab.sum() == 0:
            # stage 1 never retrieved the right item -> an honest miss.
            # Record it beyond every cutoff instead of silently dropping it,
            # otherwise we would be reporting metrics on the easy users only.
            ranks_reranked.append(10**6)
            ranks_stage1.append(10**6)
            continue
        n_lists_with_positive += 1
        pos = int(np.argmax(lab))
        ranks_reranked.append(int((pred[sl] > pred[sl][pos]).sum()))
        s1 = Xte["two_tower_score"].to_numpy()[sl]
        ranks_stage1.append(int((s1 > s1[pos]).sum()))

    importances = pd.Series(
        ranker.feature_importances_, index=Xtr.columns
    ).sort_values(ascending=False)

    return {
        "reranked": ranking_metrics(np.array(ranks_reranked)),
        "stage1_within_candidates": ranking_metrics(np.array(ranks_stage1)),
        "importances": importances,
        # Fraction of users whose true item survived stage 1 into the candidate
        # set. This is the pipeline's ceiling -- no re-ranker can beat it.
        "candidate_recall": n_lists_with_positive / len(gte),
        "n_candidates": N_CANDIDATES,
    }
